Feat/favorite
dev-debris/stock-simulator pull request #43
Opened 2023-04-06 17:27 UTC by SunNacho

1.즐겨찾기 토글 버튼 클릭 시 페이지가 기존에 보던 페이지로 고정되던 문제 수정(토글 누를 때마다 첫 페이지로 이동)

2.즐겨찾기 상태에 맞기 lastPage변수 재설정

3. 즐겨찾기 추가 후 새로고침 할 시 즐겨찾기가 렌더링되지 않는 문제 수정

4. 즐겨찾기 버튼 style변경 (검색창 임시)

2023-04-09 05:13 UTC, akh9804 commented on src/components/StockList/StockListItem.tsx
> +  const favoriteMarkets = favorites.map(x => x.market);
이런 변수는 [selector](https://recoiljs.org/docs/basic-tutorial/selectors)를 사용하면 훨씬 깔끔하게 사용할 수 있어요. `selector`는 다른 `atom`으로부터 파생된 상태를 만들고 싶을 때 사용하는 거라고 보면 될 것 같아요ㅎㅎ

```ts
// atoms/index.ts
export const favoriteMarketsState = selector({
  key: 'favoriteMarketsState',
  get: ({get}) => {
    return get(favoriteCoinListState).map(x => x.market);
  }
});

// StockListItem.tsx
const favoriteMarkets = useRecoilValue(favoriteMarketsState);
```

2023-04-09 05:13 UTC, akh9804 commented on src/components/StockList/StockListItem.tsx
> +  const isFavorite = favoriteMarkets.includes(ticker.market);
이것도 위에서 정의한 `selector`로부터 파생된 상태라고 볼 수 있으니 또다른 `selector`로 만들어서 사용하면 좋은데요.

`isFavorite`의 경우, `ticker.market`이라는 인자를 넘겨줘야 하니까 이런 경우에는 [selectorFamily](https://recoiljs.org/docs/api-reference/utils/selectorFamily/)를 사용하면 되는 것 같아요.

```ts
// atoms/index.ts
const isFavoriteMarketState = selectorFamily({
  key: 'isFavoriteMarketState',
  get: (ticker: Market) => ({get}) => {
    return get(favoriteMarketsState).includes(ticker.market);
  }
});

// StockListItem.tsx
const isFavorite = useRecoilValue(isFavoriteMarketState(ticker));
```

2023-04-09 05:27 UTC, SunNacho commented on src/components/StockList/StockListItem.tsx
> +  const favoriteMarkets = favorites.map(x => x.market);
아~애초에 atom단계에서 걸러주면 되겠군요

2023-04-09 05:28 UTC, SunNacho commented on src/components/StockList/StockListItem.tsx
> +  const isFavorite = favoriteMarkets.includes(ticker.market);
오 이런문법도 있군요..
selectorFamily는 처음 보네요..

2023-04-09 14:46 UTC, SunNacho commented on src/components/StockList/StockListItem.tsx
> +  const favoriteMarkets = favorites.map(x => x.market);
![image](https://user-images.githubusercontent.com/105419350/230779589-bec16237-e9c2-4f29-9848-f283555fef21.png)
타입 지정 오류가 뜨는것 같네요 이유가 뭘까요?

2023-04-10 00:14 UTC, akh9804 commented on src/components/StockList/StockListItem.tsx
> +  const favoriteMarkets = favorites.map(x => x.market);
흠.. 정의대로라면 타입이 맞아야 하는데 일종의 버그인 것 같아서 우회할 필요가 있을 것 같아요. 어차피 필요한 값은 `ticker.market`이니 애초에 이 속성을 넣어주는 것으로 바꿔주면 될 것 같아요.

```ts
export const isFavoriteMarketState = selectorFamily<boolean, string>({
  key: 'isFavoriteMarketState',
  get:
    market =>
    ({get}) => {
      return get(favoriteMarketsState).includes(market);
    },
});

// StockListItem.tsx
const isFavorite = useRecoilValue(isFavoriteMarketState(ticker.market));
```

2023-04-10 00:22 UTC, SunNacho commented on src/components/StockList/StockListItem.tsx
> +  const favoriteMarkets = favorites.map(x => x.market);
아..이렇게 하면 되네요 왜 이런 버그가 있던걸까용? 의아하군요

2023-04-10 00:26 UTC, SunNacho commented on src/components/StockList/StockListItem.tsx
> +  const favoriteMarkets = favorites.map(x => x.market);
근데 이렇게 되면 
`// StockListItem.tsx
const favoriteMarkets = useRecoilValue(favoriteMarketsState);`
이부분은 필요가 없어지네요. 코드가 더 짧아질것 같습니다 굿굿

2023-04-10 02:45 UTC, akh9804 commented on src/atoms/index.ts
> +  key: 'favoriteMarketsState',
요것도 `RECOIL_KEY` 사용하면 좋겠네요ㅎㅎ

2023-04-10 02:45 UTC, akh9804 commented on src/components/StockList/StockListItem.tsx
> +  const isSelected = selectedCoin[0] === ticker ? true : false;
요것도 `selectedCoin` 상태로부터 파생된 상태니까 `isFavorite`처럼 구현해보면 좋을 것 같아요:)

2023-04-10 04:20 UTC, SunNacho commented on src/atoms/index.ts
> +  key: 'favoriteMarketsState',
아 이거 어제는 RECOIL_KEY로 했는데 get타입 버그땜에 다시 하다가 잊었네요 ㅋㅋ 통일하겠습니당

2023-04-10 04:20 UTC, SunNacho commented on src/components/StockList/StockListItem.tsx
> +  const isSelected = selectedCoin[0] === ticker ? true : false;
오 예제 학습후 유제 풀기라.. 이거 절대 못참거든요

2023-04-10 04:57 UTC, SunNacho commented on src/atoms/index.ts
> +    market =>
1. market이 아니라 ticker를 사용하려 했는데, ticker의 타입인 Market을 selectorFamily의 두번째 매개변수로 지정하니 지정할 수 없는 타입이라 하더라구요, 그래서 market을 전달하기로 하고 return get(selectedMarketState)[0].market ===market으로 하려고 했습니다.

2023-04-10 04:57 UTC, SunNacho commented on src/atoms/index.ts
> +export const selectedMarketState = selector({
2. 그런데 maket 속성을 찾지 못하더라구요, 그래서 위의 예시처럼 selectedMarketState로 우회해서 market을 선언했습니다. 왜 두개나 사용했을지 궁금하실까봐.. !!

2023-04-10 12:20 UTC, akh9804 approved these changes

2023-04-12 09:05 UTC, HojinAn requested changes
리뷰 폭탄 받아라~

2023-04-12 09:05 UTC, HojinAn commented on src/atoms/index.ts
> +});
```suggestion
export const isSelectedCoinState = selectorFamily<boolean, string>({
  key: RECOIL_KEY.isSelectedCoin,
  get:
    market =>
    ({get}) => {
      return get(selectedCoinState)?.market === market;
    },
});
```

이 부분도 마찬가지! 앞서 말한대로 굳이 selector로 따로 만들 필요가 없다고 생각해요 ㅎㅎ  
이 코드는 제가 위에서 `selectedCoinState`를 `Market | null`로 지정해서 이렇게 코드가 나오네요~  
배열은 해당 state의 이름과는 어울리지 않다고 생각합니다 ㅎㅎ

2023-04-12 09:05 UTC, HojinAn commented on src/components/StockList/StockListItem.tsx
> +  const isSelected = useRecoilValue(isSelectedCoinState(ticker.market));
현재로써는 이 `isSelected` 값이 색깔 변경 외에는 사용되지 않고 있는거죠?
그러면 이 값이 전역으로 있을 필요가 있나요?? 또 다른 곳 어디에서 사용 될 예정인가요??

2023-04-12 09:37 UTC, SunNacho commented on src/atoms/index.ts
> +    market =>
콘솔창에 serialazable이라고 뜬건 봤는데 뭔지 찾아봐야겠네요

2023-04-12 09:39 UTC, SunNacho commented on src/atoms/index.ts
> +});
저도 이거 합치면 좋겠다 생각했는데, selector가 익숙하지 않아서 포기했거든요
그냥 간단하게 생각하면 되는군요

2023-04-12 09:40 UTC, SunNacho commented on src/atoms/index.ts
>  });
음 어차피 단일개체만 저장하는 형식이니 market으로 바꾸는게 나을것 같기도 하네요!

2023-04-12 09:42 UTC, SunNacho commented on src/atoms/index.ts
> +});
음 이러면 더 깔끔해지네요!

2023-04-12 09:43 UTC, SunNacho commented on src/components/StockList/StockListItem.tsx
> +  const isSelected = useRecoilValue(isSelectedCoinState(ticker.market));
아 선택한 코인을 저장해둔 이유는 코인을 선택했을 때에 해당 코인의 정보(차트, 고가, 저가, 현재가) 등등을 화면 우측에 띄울 수 있게하기 위함입니다! 내가 어떤 코인을 선택했는지를 전역으로 관리해야 다른 컴포넌트에서 사용할 수 있을 것 같아서요

2023-04-13 06:01 UTC, SunNacho commented on src/atoms/index.ts
> +    market =>
객체를 문자열로 바꾸는 작업(ex JSON)등 을 직렬화라고 부르는군요, 그 반대는 역직렬화, 혹은 Parsing이라고.. 하나 알아갑니다!

2023-04-13 07:03 UTC, akh9804 commented on src/atoms/index.ts
>  });
저도 좋아요!

2023-04-15 08:19 UTC, HojinAn approved these changes

2023-04-15 08:19 UTC, merged