refactor: app
dev-debris/stock-simulator pull request #52
Opened 2023-05-08 14:05 UTC by HojinAn

## 변경 사항

- 코드를 정리하고 CoinList로 바뀐 부분들을 적용했습니다.

2023-05-13 03:34 UTC, akh9804 requested changes

2023-05-13 03:34 UTC, akh9804 commented on src/components/CoinDetail/CoinDetail.tsx
> +        <Chart type={'candlestick'} {...chartData} />
`ChartWrapper` 태그부터 `CoinDetailChart` 컴포넌트로 대체할 수 있지 않을까요~? 현재는 `CoinDetailChart` 컴포넌트가 사용되는 곳이 없는 것 같아서요!

2023-05-13 03:34 UTC, akh9804 commented on src/components/CoinDetail/CoinDetailChart.tsx
> +import StockDetailChartOptions from './CoinDetailChartOptions';
요것도 `Coin~~~`으로 수정하면 좋을 것 같네요ㅎㅎ

2023-05-13 13:34 UTC, SunNacho approved these changes
깔끔하게 정리 됐네요!! 굿굿

2023-05-20 05:06 UTC, akh9804 commented on src/components/CoinDetail/Chart/CoinDetailChart.tsx
> +      {data.length > 0 ? (
`data` 길이 체크를 if 문으로 하는 건 어때요? 가독성 측면에서 좋지 않을까 싶어요ㅎㅎ

```ts
if (!data.length) {
  return null;
}

return (
  ...
)
```

2023-05-20 05:06 UTC, akh9804 commented on src/components/Container.tsx
> +function Container({children}: PropsWithChildren) {
오 React 내장 타입으로 존재하는 거였군여..!!

2023-05-20 05:06 UTC, akh9804 commented on src/hooks/queries/useDayCandleQuery.ts
> +    enabled: !!request.queries.market,
요걸 추가한 이유는 어떤 거에요?? 궁금해서 여쭤봅니당

2023-05-21 16:10 UTC, HojinAn commented on src/components/Container.tsx
> +function Container({children}: PropsWithChildren) {
회사에서 배운 타입입네당 후후

2023-05-21 16:11 UTC, HojinAn commented on src/components/CoinDetail/Chart/CoinDetailChart.tsx
> +      {data.length > 0 ? (
반영 완료!

2023-05-21 16:15 UTC, HojinAn commented on src/hooks/queries/useDayCandleQuery.ts
> +    enabled: !!request.queries.market,
getDaysCandles에서 market이 required라서 queries 안에 market이 없으면 요청을 안하도록 막았습니다! default 값을 주기보다는 특정 값이 없으면 호출하지 않도록 해주는 게 더 맞다 판단했어요 ㅎㅎ

2023-05-21 23:42 UTC, akh9804 approved these changes

2023-05-21 23:43 UTC, akh9804 commented
PR 메시지를 적절하게 변경하고 머지하면 좋을 것 같아요ㅎㅎ

2023-05-22 11:03 UTC, merged